[package]
name = "readpassphrase-3"
version = "0.9.4"
edition = "2021"
rust-version = "1.77.0"
description = "Simple wrapper around readpassphrase(3)"
readme = "README.md"
repository = "https://github.com/mrdomino/readpassphrase-3"
license = "Apache-2.0 OR MIT"
keywords = ["getpass", "passphrase", "password", "tty"]
categories = ["command-line-interface"]

exclude = [
    ".githook/*",
    ".github/**",
    ".gitignore",
]

[[example]]
name = "pass"
path = "examples/pass.rs"
doc-scrape-examples = true

[[example]]
name = "inplace"
path = "examples/inplace.rs"

[[example]]
name = "owned"
path = "examples/owned.rs"

[dependencies]
bitflags = "2"
zeroize = { version = "1", optional = true }

[target.'cfg(target_os = "linux")'.build-dependencies]
pkg-config = "0.3"

[target.'cfg(target_os = "windows")'.build-dependencies]
cc = "1"

[dev-dependencies]
zeroize = "1"

[package.metadata.docs.rs]
features = ["zeroize"]
# XXX cc is crashing on mac and windows on docs.rs
no-default-features = true
