[package]
name = "readpassphrase-3"
version = "0.1.0"
edition = "2024"
description = "Simple wrapper around readpassphrase(3)"
readme = "README.md"
repository = "https://github.com/mrdomino/readpassphrase-3"
license-file = "LICENSE"
keywords = ["tty", "passphrase", "password"]
categories = ["command-line-interface"]

[dependencies]
bitflags = "2"
thiserror = { version = "2", default-features = false }
zeroize = "1"

[build-dependencies]
cc = "1"
