[package]
name = "readpassphrase-3"
version = "0.6.0-pre.0"
edition = "2024"
description = "Simple wrapper around readpassphrase(3)"
readme = "README.md"
repository = "https://github.com/mrdomino/readpassphrase-3"
license = "BSD-1-Clause"
keywords = ["tty", "passphrase", "password"]
categories = ["command-line-interface"]

exclude = [
    ".githook/*",
    ".github/**",
    ".gitignore",
]

[package.metadata.docs.rs]
features = ["zeroize"]

[dependencies]
bitflags = "2"
zeroize = { version = "1", optional = true }

[build-dependencies]
cc = "1"

[dev-dependencies]
zeroize = "1"
