[package]
name = "readpassphrase-3"
version = "0.3.2"
edition = "2024"
description = "Simple wrapper around readpassphrase(3)"
readme = "README.md"
repository = "https://github.com/mrdomino/readpassphrase-3"
license-file = "LICENSE"
keywords = ["tty", "passphrase", "password"]
categories = ["command-line-interface"]

exclude = [
  ".githooks/*",
  ".github/**",
  ".gitignore",
]

[features]
default = ["zeroize"]

[dependencies]
bitflags = "2"
zeroize = { version = "1", optional = true }

[build-dependencies]
cc = "1"
