[package]
name = "readpassphrase-3"
version = "0.6.0-pre.6"
edition = "2024"
description = "Simple wrapper around readpassphrase(3)"
readme = "README.md"
repository = "https://github.com/mrdomino/readpassphrase-3"
license = "BSD-1-Clause"
keywords = ["getpass", "passphrase", "password", "tty"]
categories = ["command-line-interface"]

exclude = [
    ".githook/*",
    ".github/**",
    ".gitignore",
]

[package.metadata.docs.rs]
rustc-args = ["--features", "zeroize"]

[features]
default = ["cc"]

[dependencies]
bitflags = "2"
zeroize = { version = "1", optional = true }

[build-dependencies]
cc = { version = "1", optional = true }

[dev-dependencies]
zeroize = "1"
