name: CI
on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:

jobs:
  build:
    name: cargo build
    strategy:
      matrix:
        os: [ubuntu, macos]
        args: ["", "--no-default-features"]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo build ${{ matrix.args }} --all-targets

  lint:
    name: cargo fmt && cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy,rustfmt
      - uses: actions-rust-lang/rustfmt@v1
      - run: cargo clippy

  publish:
    name: cargo publish
    runs-on: ubuntu-latest
    needs: [build, lint]
    environment: crates-io
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - uses: actions/attest-build-provenance@v2
        with:
          subject-path: target/package/readpassphrase-3-*.crate
