name: CI
on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:

jobs:
  build:
    name: cargo build
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        toolchain: ["nightly"]
        include:
          - os: ubuntu
            toolchain: 1.77.0
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: setup environment
        shell: bash
        run: |
          if [[ ${{ matrix.os }} = windows ]]; then
            echo suffix=.exe
          else
            echo suffix=
          fi >> $GITHUB_ENV
          if [[ ${{ matrix.os }} = ubuntu ]]; then
            sudo sh -c 'apt-get update && apt-get -y install libbsd-dev'
          fi
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: cargo build --all-targets --no-default-features
        id: no-default
        continue-on-error: true
      - uses: actions/upload-artifact@v4
        if: ${{ steps.no-default.outcome == 'success' }}
        with:
          name: pass-${{ matrix.os }}-nodefault-${{ matrix.toolchain }}
          path: target/debug/examples/pass${{ env.suffix }}
      - run: cargo build --all-targets
      - uses: actions/upload-artifact@v4
        with:
          name: pass-${{ matrix.os }}-${{ matrix.toolchain }}
          path: target/debug/examples/pass${{ env.suffix }}
      - run: cargo build --all-targets --features=zeroize
      - uses: actions/upload-artifact@v4
        with:
          name: pass-${{ matrix.os }}-zeroize-${{ matrix.toolchain }}
          path: target/debug/examples/pass${{ env.suffix }}
      - run: cargo test
      - run: cargo test --features=zeroize

  lint:
    name: cargo fmt && cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy,rustfmt
      - uses: actions-rust-lang/rustfmt@v1
      - run: cargo clippy

  publish:
    name: cargo publish
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      id-token: write
      attestations: write
    runs-on: ubuntu-latest
    needs: [build, lint]
    environment: crates-io
    steps:
      - uses: actions/checkout@v5
      - run: cargo publish --dry-run
      - uses: rust-lang/crates-io-auth-action@v1
        id: auth
      - uses: actions/attest-build-provenance@v2
        with:
          subject-path: target/package/readpassphrase-3-*.crate
      - run: cargo publish --no-verify --locked
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
