name: CI
on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:

jobs:
  build:
    name: cargo build
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        args: ["", "--no-default-features"]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - run: |
          if [[ ${{ matrix.os }} = windows ]]; then
            echo suffix=.exe
          else
            echo suffix=
          fi >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo build ${{ matrix.args }} --all-targets
      - uses: actions/upload-artifact@v4
        with:
          name: pass
          path: target/debug/examples/pass${{ env.suffix }}
      - run: cago test ${{ matrix.args }}

  lint:
    name: cargo fmt && cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy,rustfmt
      - uses: actions-rust-lang/rustfmt@v1
      - run: cargo clippy

  publish:
    name: cargo publish
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      id-token: write
      attestations: write
    runs-on: ubuntu-latest
    needs: [build, lint]
    environment: crates-io
    steps:
      - uses: actions/checkout@v4
      - run: cargo publish --dry-run
      - uses: actions/attest-build-provenance@v2
        with:
          subject-path: target/package/readpassphrase-3-*.crate
      - run: cargo publish --no-verify --locked
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
